# Can You Flip the Coins Exactly as You’d Expect? (2023.11.17)

mathematical puzzle of the week: https://thefiddler.substack.com/p/can-you-flip-the-coins-exactly-as

## II. Extra Credit

In [4]:
import numpy as np
import math

In [5]:
def weak_compositions(boxes, balls, parent=tuple()): 
  """ 
  Generator to create an array for a weak composition
   source code from: https://stackoverflow.com/questions/4647120/next-composition-of-n-into-k-parts-does-anyone-have-a-working-algorithm
  """
  if boxes > 1:
    for i in range(balls + 1):
      for x in weak_compositions(boxes - 1, i, parent + (balls - i,)):
        yield x
  else:
    yield parent + (balls,)

In [17]:
n_rounds = 8 	# number of rounds
n_outcome = 4 	# number of possible outcomes (0, 1, 2 or 3 heads)

In [18]:
compositions = np.fromiter(			 
	weak_compositions(n_outcome, n_rounds), 
	dtype=np.dtype((int, n_outcome))) 	# array with the (weak) compositions of the outcome

n_compositions = len(compositions) 		# number of all compositions

In [19]:
# Calculate the probabilty of all compositions.
# This requires the number of different permutations for one composition and the probability 
# of these permutations.

weights = np.array([1/8, 3/8, 3/8, 1/8]) 	# probabilities of outcome (0, 1, 2 and 3 heads)

prob_of_permutation =  np.prod(weights ** compositions, axis=1) # probabilites for one permutation for the 'compositions' array

# calculate the number of permutations
occurence = []
for j in range(n_compositions):
	occurence.append(
		(40320/math.prod([			# 8! = 40320
			math.factorial(compositions[j][i]) 
			for i in range(n_outcome)])))


prob_results = prob_of_permutation * occurence # array with probabilities of the compositions 

In [25]:
# To get the ordered quadruple (a, b, c, d) we sort the 'compositions' array and create a unique array from that sorted list.  

def sort_row(row):
    return np.sort(row)[::-1]

compositions_sorted = np.apply_along_axis(sort_row, axis=1, arr=compositions)

quadruple = np.unique(compositions_sorted,axis=0)[::-1]


In [ ]:
# Calculate the probability of each quadruple (a, b, c, d)

quadruple_prob = []
for index, value in enumerate(quadruple):
	prob_indices = np.where(np.all(compositions_sorted == value, axis=1))[0]
	quadruple_prob.append(np.sum(prob_results[prob_indices]))


In [43]:
# Print the results in an ordered list.

sort_index = np.argsort(quadruple_prob)[::-1]

for index, value in enumerate(sort_index):
	print(f'{quadruple[value]}: {100*quadruple_prob[value]:2.2f}%')


[4 3 1 0]: 17.50%
[3 2 2 1]: 14.06%
[5 2 1 0]: 12.81%
[4 2 1 1]: 12.80%
[3 3 2 0]: 8.53%
[4 2 2 0]: 8.20%
[3 3 1 1]: 7.09%
[5 3 0 0]: 4.74%
[6 1 1 0]: 3.42%
[5 1 1 1]: 2.96%
[4 4 0 0]: 2.87%
[6 2 0 0]: 2.68%
[2 2 2 2]: 1.22%
[7 1 0 0]: 1.04%
[8 0 0 0]: 0.08%
